name: statemanagmenetstacked
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  package_info: ^2.0.2

  # State Managment  
  stacked: 
  stacked_services:

  # SVG
  flutter_svg: ^0.22.0


  # Animations
  animations: ^2.0.1


  # ICONS
  cupertino_icons: ^1.0.2


  # Storage

  shared_preferences: ^2.0.0


  #scroll
  scroll_to_index: ^2.0.0
  scroll_date_picker: ^2.0.5

  #date
  intl: ^0.17.0
  timeago: ^3.1.0

  
  #charts circular sleek slider
  sleek_circular_slider: ^2.0.1


  # Http
  dio: ^4.0.0

  # Google Fonts
  google_fonts: ^2.1.0

  # 
  wave: ^0.2.0

  liquid_progress_indicator: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  stacked_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Spartan
      fonts:
        - asset: assets/fonts/Spartan-Bold.ttf

    - family: "Saira"
      fonts:
      - asset: assets/fonts/Saira-Thin.ttf
        weight: 200

    - family: SunFlower
      fonts:
        - asset: assets/fonts/Sunflower-Light.ttf
          weight: 200
        - asset: assets/fonts/Sunflower-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sunflower-Medium.ttf


    - family: Sansation
      fonts:
        - asset: assets/fonts/Sansation_Bold_Italic.ttf
          style : italic
          weight: 700
        - asset: assets/fonts/Sansation_Bold.ttf
          weight: 700
        - asset: assets/fonts/Sansation_Italic.ttf
          style : italic
        - asset: assets/fonts/Sansation_Light_Italic.ttf
          style : italic
          weight: 300
        - asset: assets/fonts/Sansation_Light.ttf
          weight: 300
        - asset: assets/fonts/Sansation_Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
